ARGO-4178 Optimize xml parsing with lxml
ARGOeu/argo-connectors pull request #252
Opened 2023-01-10 12:58 UTC by deksa89

2023-01-10 13:03 UTC, deksa89 commented
merge this branch after refactor-plainjson-write branch

2023-01-26 16:41 UTC, vrdel commented on modules/io/jsonwrite.py
> +class JsonWriter():
Derive here from "object", so `class JsonWriter(object)`. `object` is base for all new classes - starting from Python 2. Check for example https://stackoverflow.com/questions/4015417/why-do-python-classes-inherit-object

2023-01-26 17:21 UTC, vrdel commented on modules/parse/base.py
> +    def parse_url_endpoints_lxml(self, endpoints_node):
Preserve old name of methods without `_lxml` suffix.

2023-01-26 17:23 UTC, vrdel commented on tests/test_servicetypefeed.py
>          self.assertEqual(service_types,
Fix indents here.

2023-01-26 17:27 UTC, vrdel requested changes
Next to single comments provided in PR, I'm also seeing:
* `parse_xml()` in `base.py` still rely on old library
* `ExpatError` handling that is leftover from previous library
* imports of old library like `import xml.dom...` and `from xml.parsers...`

Take care of these also.

2023-02-23 18:14 UTC, vrdel requested changes
You need to parse `NOTIFICATIONS` field for service endpoints and service groups as well. Currently, you're doing it only for sites. Take a look at my branch `notif-flag-honor` and check there at `gocdb_topology.py` how I'm doing it for the rest of topology components.

Also, there's a new config option that you need to place in `customer.conf` file to test it - example:
```
[CUSTOMER_SDC]
....
HonorNotificationFlag = True
....
```

2023-02-27 13:48 UTC, vrdel commented
Merging and fixing in later PRs.

2023-02-27 13:48 UTC, merged